### PR TITLE
Resolve for node modules from the current working directory

### PR DESCRIPTION
**Pull request by lewismorgan**
Suggested fix for #CRKA-83

Resolve currently only works from the create-react-kotlin-app's installed packages.

### CODE REVIEW

**Comment by huston007** [comment]
THanks. We should check how this works on Windows

**Comment by huston007** [comment]
@lewismorgan I'm afraid the e2e tests have failed after this change:
`Module not found: Error: Can't resolve 'kotlinApp' in '/mnt/agent/work/e302b02dcd854820/packages/react-scripts'`

**Comment by lewismorgan** [comment]
Thank you. Amended the commit with changes that I think will be much more acceptable after some more research. This one should be looking in all the node_modules paths now, actually adding the cwd this time instead of forcing it. Makes sense why the end to end tests failed after thinking about it.

**Comment by lewismorgan** [comment]
Build checks look like it's using Node 6. Adding paths to resolve needs at least v8.9.0

https://nodejs.org/docs/latest/api/modules.html#modules_require_resolve_paths_request

I'm not sure what a better approach would be, please let me know what you think is best.

**Comment by huston007** [comment]
@lewismorgan It would be better for us to keep backward compatibility as long as possible. Could we use this paths only if node version is high enough and fallback to previous approach otherwise?

**Comment by Leonya** [comment]
The build is now green, should I merge it?

**Comment by huston007** [comment]
@Leonya Yep, thanks

**Pull request merged**
