### PR TITLE
Update to kotlin react 16.9.0 pre.82

### PR DESCRIPTION
**Pull request by trevordilley**
Simply updates to the most recent version of kotlin-react and related dependencies. 

Had to add  `kotlinx-coroutines-core` because the app wouldn't build without it. 

Updated README.md, removing the line mentioning kotlinx since it's now required.

### CODE REVIEW

**Comment by trevordilley** [comment]
@huston007 looking at the commit history it looks like you're the last human being to commit to this repo. Curious if this PR meets the requirements to merge, if so I think it would be a real good idea to update this project to use the modern react-wrappers, otherwise folks are experiencing a dated and subpar experience with kotlin-react!

**Comment by Leonya** [comment]
Sorry, this has slipped past me. Will merge and release tomorrow.

**Comment by trevordilley** [comment]
@Leonya thanks!

**Comment by Leonya** [comment]
Released:

- create-react-kotlin-app@2.0.0
- @jetbrains/gen-idea-libs@2.0.0
- @jetbrains/kotlin-webpack-plugin@3.0.0
- @jetbrains/kotlinc-js-api@2.0.0
- react-scripts-kotlin@4.0.1
- @jetbrains/ts2kt-automator@2.0.0

**Comment by trevordilley** [comment]
Darn, I was looking forward to being on the record as a contributor to a Kotlin thing :( Thanks for updating things thought @Leonya !

**Pull request closed without merging**
